### ISSUE TITLE
person_domain table problem

### ISSUE THREAD

**Issue by sebDK** [exanpe/exa-grails-plugins#7]
Hi there,

I am trying to use "fr.exanpe.grails:exa-datatables:2.0.0" on an existing database with existing tables.
I am using `grails.3.2.0`
That is why my datasource settings look like:

```
development:

        dataSource:

           dbCreate: validate
#           logSql: true
           driverClassName: oracle.jdbc.OracleDriver
           url: jdbc:oracle:thin:@myserver:1521:proddb
           username: myuser
           password: mypass
           dialect: org.hibernate.dialect.Oracle10gDialect
```
     
The problem is that I get the following mistake:
`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.orm.hibernate.HibernateDatastore]: Constructor threw exception; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [person_domain] `

The `person_domain` is coming from the plugin and should be excluded but apparently it is not.
Can you help with that?

BR,

Sébastien
